resources:
- repo: self
  clean: true
queue:
  name: Hosted VS2017
  
variables:
  BuildConfiguration: release
  MajorVersion: 0
  MinorVersion: 1

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.8.0'
  inputs:
    versionSpec: 4.8.0


- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: src/IListsExtension.sln


- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: 'src/**/*.csproj'

    arguments: '-c  $(BuildConfiguration)'


- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack

    packagesToPack: src/IListExtension/IListExtension.csproj

    versioningScheme: byPrereleaseNumber

    majorVersion: '$(MajorVersion)'

    minorVersion: '$(MinorVersion)'

    patchVersion: '$(Build.BuildNumber)'

    includeSymbols: true


- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'