name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '2.2.x'
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~\.nuget\packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/project.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build .NET projects
        run: dotnet build src/IListsExtension.sln --configuration Release
      - name: Run .NET tests
        run: dotnet test src/IListsExtension.sln --configuration Release --no-build
